#!/usr/bin/env python3
"""
Add a "current-frame LiDAR BEV" image to each data entry in train_bev_base.jsonl:
  - images: insert lidar_bev/<frame>.png at index 10
            (after the 6 current views, before the 5 future BEVs -- ad_collator uses .pop() to take the last 5 as DINOv3 targets,
             so the lidar lands in the LLM visual segment and won't be mistaken for a target)
  - prompt: insert a sentence with <image> after the six-view sentence, raising the <image> count 10 -> 11, matching the first 11 LLM visual inputs

The LiDAR BEV image is generated by tools/batch_lidar_to_bev.py and stored at <scene>/lidar_bev/<frame>.png.

Usage:
  python dataprocess/add_lidar_bev_to_jsonl.py --limit 3 --dry      # verify the first few entries
  python dataprocess/add_lidar_bev_to_jsonl.py                      # write out all entries
"""
import os
import json
import argparse

LIDAR_SENTENCE = (
    "This is the current-frame LiDAR bird's-eye view (top-down, 35 m around the ego): "
    "the center yellow dot is the ego vehicle; concentric rings are LiDAR ground returns; "
    "bright red marks tall objects (vehicles, walls, buildings, obstacles, trees); "
    "black is empty or occluded space. LiDAR BEV:<image>."
)


def process(d):
    images = d["images"]
    cur = images[4]  # current-frame rgb_front
    scene_dir = cur.split("/camera/")[0]
    frame = os.path.splitext(os.path.basename(cur))[0]
    bev = os.path.join(scene_dir, "lidar_bev", frame + ".png")

    images.insert(10, bev)  # insert after the 6 current views, before the 5 future BEVs

    uc = d["messages"][0]["content"]
    lines = uc.split("\n")
    for i, l in enumerate(lines):
        if "six-view images" in l:
            lines.insert(i + 1, LIDAR_SENTENCE)
            break
    d["messages"][0]["content"] = "\n".join(lines)
    return d, bev


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in_jsonl", default="/home/s56cai/DeepSight/data/train_bev_base.jsonl")
    ap.add_argument("--out_jsonl", default="/home/s56cai/DeepSight/data/train_bev_base_lidar.jsonl")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--dry", action="store_true", help="only print the first few entries, do not write the file")
    a = ap.parse_args()

    n = miss = 0
    out = None if a.dry else open(a.out_jsonl, "w")
    with open(a.in_jsonl) as f:
        for i, line in enumerate(f):
            if a.limit and i >= a.limit:
                break
            d = json.loads(line)
            d, bev = process(d)
            if not os.path.exists(bev):
                miss += 1
            n += 1
            if a.dry and i < 3:
                uc = d["messages"][0]["content"]
                print(f"\n===== data {i} =====")
                print("\n".join(uc.split("\n")[:3]))
                print(f"[#<image>={uc.count('<image>')}] [#images={len(d['images'])}] "
                      f"[images[10]={d['images'][10]} exists:{os.path.exists(d['images'][10])}]")
            if out:
                out.write(json.dumps(d, ensure_ascii=False) + "\n")
    if out:
        out.close()
    print(f"\nprocessed {n}  missing_bev {miss}" + ("  (dry-run)" if a.dry else f"  -> {a.out_jsonl}"))


if __name__ == "__main__":
    main()
